#!/usr/bin/env bash
set -euo pipefail

# =====================================
# Edit Here: TTRL-OR Colocate Defaults
# =====================================
# Official TRL/vLLM colocate style on a single machine:
# - multi-process distributed launch via accelerate
# - one rank per visible GPU
# - each rank trains on its local GPU
# - colocated vLLM shares the same GPUs for generation

export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0,1}"
NPROC_PER_NODE=2
MASTER_ADDR=127.0.0.1
MASTER_PORT=29521
NUM_MACHINES=1
MACHINE_RANK=0
ACCELERATE_MIXED_PRECISION=no
ACCELERATE_CONFIG_FILE="scripts/accelerate_colocate.yaml"

BACKEND=trl
MODEL_NAME_OR_PATH="${MODEL_NAME_OR_PATH:-$HOME/model/Qwen/Qwen2.5-7B-Instruct}"
DATASET_JSONL="${DATASET_JSONL:-data/IndustryOR_fixedV2.jsonl}"
DATASET_START_INDEX=0
DATASET_LIMIT=0
RESUME_SKIP_COMPLETED=true
LOG_DIR="${LOG_DIR:-logs/run_colocate}"
OUT_JSON="${OUT_JSON:-outputs/run_colocate.json}"

# MCTS
MAX_ITERATIONS=20
C_PUCT=1.414
MCTS_STOP_ON_REWARD_ONE=false
SOLVERLLM_COMPARE_MODE=true

# Reward
REWARD_CLUSTER_SCOPE=local
GLOBAL_CONSENSUS_REL_TOL=0.005
ENABLE_R3_REWARD=false
ROBUSTNESS_CASES=3

# GRPO
GRPO_LR=1e-4
GRPO_TRAIN_EPOCHS=1
GRPO_CLIP_EPSILON=0.3
GRPO_CLIP_EPSILON_HIGH=-1
GRPO_NUM_GENERATIONS=8
GRPO_GENERATION_BATCH_SIZE=0
GRPO_MAX_COMPLETION_LEN=4096

# Generation
TEMPERATURE=1.0
TOP_P=0.95
MAX_NEW_TOKENS=4096

# vLLM colocate
USE_VLLM=true
VLLM_MODE=colocate
# For 2 GPUs, start from 1 if you want each rank to keep its own local engine.
# Set to 2 when you explicitly want one TP group spanning both GPUs.
VLLM_TENSOR_PARALLEL_SIZE=1
VLLM_GPU_MEMORY_UTILIZATION=0.35
VLLM_MAX_MODEL_LEN=10240
VLLM_MAX_NUM_BATCHED_TOKENS=32768
GRPO_VLLM_ENABLE_SLEEP_MODE=false

# LoRA
LORA_R=8
LORA_ALPHA=16
LORA_DROPOUT=0.05
LORA_BIAS=none
LORA_TARGET_MODULES=q_proj,k_proj,v_proj,o_proj,gate_proj,up_proj,down_proj

# Misc
SEED=7
TORCH_DTYPE=auto
TRUST_REMOTE_CODE=false

# Important:
# - Do NOT start scripts/start_vllm_server.sh for colocate mode.
# - `accelerate launch` will be used automatically by scripts/run.sh when NPROC_PER_NODE>1.
# - For 2-GPU colocate, keep CUDA_VISIBLE_DEVICES=0,1 and NPROC_PER_NODE=2.
# - VLLM_TENSOR_PARALLEL_SIZE controls how many GPUs one vLLM model replica spans.
#   * 1: each rank uses its own local vLLM engine (good starting point)
#   * 2: both GPUs form one TP group for vLLM generation

CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES}" \
NPROC_PER_NODE="${NPROC_PER_NODE}" \
MASTER_ADDR="${MASTER_ADDR}" \
MASTER_PORT="${MASTER_PORT}" \
NUM_MACHINES="${NUM_MACHINES}" \
MACHINE_RANK="${MACHINE_RANK}" \
ACCELERATE_MIXED_PRECISION="${ACCELERATE_MIXED_PRECISION}" \
ACCELERATE_CONFIG_FILE="${ACCELERATE_CONFIG_FILE}" \
BACKEND="${BACKEND}" \
MODEL_NAME_OR_PATH="${MODEL_NAME_OR_PATH}" \
DATASET_JSONL="${DATASET_JSONL}" \
DATASET_START_INDEX="${DATASET_START_INDEX}" \
DATASET_LIMIT="${DATASET_LIMIT}" \
RESUME_SKIP_COMPLETED="${RESUME_SKIP_COMPLETED}" \
LOG_DIR="${LOG_DIR}" \
OUT_JSON="${OUT_JSON}" \
MAX_ITERATIONS="${MAX_ITERATIONS}" \
C_PUCT="${C_PUCT}" \
MCTS_STOP_ON_REWARD_ONE="${MCTS_STOP_ON_REWARD_ONE}" \
SOLVERLLM_COMPARE_MODE="${SOLVERLLM_COMPARE_MODE}" \
REWARD_CLUSTER_SCOPE="${REWARD_CLUSTER_SCOPE}" \
GLOBAL_CONSENSUS_REL_TOL="${GLOBAL_CONSENSUS_REL_TOL}" \
ENABLE_R3_REWARD="${ENABLE_R3_REWARD}" \
ROBUSTNESS_CASES="${ROBUSTNESS_CASES}" \
GRPO_LR="${GRPO_LR}" \
GRPO_TRAIN_EPOCHS="${GRPO_TRAIN_EPOCHS}" \
GRPO_CLIP_EPSILON="${GRPO_CLIP_EPSILON}" \
GRPO_CLIP_EPSILON_HIGH="${GRPO_CLIP_EPSILON_HIGH}" \
GRPO_NUM_GENERATIONS="${GRPO_NUM_GENERATIONS}" \
GRPO_GENERATION_BATCH_SIZE="${GRPO_GENERATION_BATCH_SIZE}" \
GRPO_MAX_COMPLETION_LEN="${GRPO_MAX_COMPLETION_LEN}" \
TEMPERATURE="${TEMPERATURE}" \
TOP_P="${TOP_P}" \
MAX_NEW_TOKENS="${MAX_NEW_TOKENS}" \
USE_VLLM="${USE_VLLM}" \
VLLM_MODE="${VLLM_MODE}" \
VLLM_TENSOR_PARALLEL_SIZE="${VLLM_TENSOR_PARALLEL_SIZE}" \
VLLM_GPU_MEMORY_UTILIZATION="${VLLM_GPU_MEMORY_UTILIZATION}" \
VLLM_MAX_MODEL_LEN="${VLLM_MAX_MODEL_LEN}" \
VLLM_MAX_NUM_BATCHED_TOKENS="${VLLM_MAX_NUM_BATCHED_TOKENS}" \
GRPO_VLLM_ENABLE_SLEEP_MODE="${GRPO_VLLM_ENABLE_SLEEP_MODE}" \
LORA_R="${LORA_R}" \
LORA_ALPHA="${LORA_ALPHA}" \
LORA_DROPOUT="${LORA_DROPOUT}" \
LORA_BIAS="${LORA_BIAS}" \
LORA_TARGET_MODULES="${LORA_TARGET_MODULES}" \
SEED="${SEED}" \
TORCH_DTYPE="${TORCH_DTYPE}" \
TRUST_REMOTE_CODE="${TRUST_REMOTE_CODE}" \
bash ./scripts/run.sh

